Repository CollaboraOnline/online, pull requests merged in 2020-10, with the labels that each got.

#219 Add alt text to generated buttons
  loleaflet/src/control/Control.JSDialogBuilder.js
  loleaflet/src/control/Control.NotebookbarBuilder.js
Labels: accessibility

#222 Notebookbar: avoid duplicated unused ids
  loleaflet/src/control/Control.NotebookbarBuilder.js
Labels: accessibility

#204 leaflet: specialise cursor for impress text
  loleaflet/css/leaflet.css
  loleaflet/src/layer/marker/Cursor.js
Labels: UX, enhancement

#263 wsd: correction in conversion from timestamp to ISO8601
  common/Util.cpp
  test/WhiteBoxTests.cpp
Labels: bug

#206 leaflet: specialise cursor for impress text
  loleaflet/css/leaflet.css
  loleaflet/src/layer/marker/Cursor.js
Labels: UX, enhancement
