Repository CollaboraOnline/online, pull requests merged in 2024-10, with the labels that each got.

#10153 private/marco/slideshow shape animations in webgl
  browser/src/slideshow/LayerDrawing.ts
  browser/src/slideshow/LayerRenderer.ts
  browser/src/slideshow/engine/AnimatedElement.ts
Labels: CODE "red"

#10126 Create contributor_fetch.yml
  .github/workflows/contributor_fetch.yml
Labels: CODE "red"

#10109 Fix : Automatic focus jump during tab navigation
  browser/src/control/Control.JSDialog.js
Labels: CODE "red"

#9702 contextmenu: add support to insert and remove data labels on charts
  browser/src/control/Control.ContextMenu.js
  browser/src/unocommands.js
Labels: CODE "red"

#10232 TileCombined::toAABBox(): Return const reference, avoiding copy
  wsd/TileDesc.hpp
Labels: enhancement, 24.04

#10251 Rename UnitWSD::config{ure -> Net}, to allow -Woverloaded-virtual
  common/Unit.hpp
  test/UnitTimeoutConnections.cpp
  test/UnitTimeoutNone.cpp
  test/UnitTimeoutSocket.cpp
  test/UnitTimeoutWSPing.cpp
  wsd/COOLWSD.cpp
Labels: 24.04

#10233 docs(mobile): Mention co-24.04-mobile in README
  README.md
Labels: documentation, android, ios

#10297 user following: do not turn off when typing
  browser/src/layer/marker/TextInput.js
Labels: CODE "red"

#10295 Fix TypeError in _syncTilePanePos
  browser/src/layer/tile/CanvasTileLayer.js
Labels: CODE "red"

#10298 Fix regression in `Socket::shutdown()` when having `_noShutdown` set
  net/Socket.hpp
Labels: 24.04

#9139 admin: add dockey to adddoc message
  wsd/AdminModel.cpp
  wsd/protocol.txt
Labels: draft

#10325 Remove disabled `StreamSocket::checkRemoval` criteria minimum throughput
  net/NetUtil.hpp
  net/Socket.cpp
  net/Socket.hpp
  test/Makefile.am
  test/UnitTimeoutConnections.cpp
  test/UnitTimeoutNone.cpp
  test/UnitTimeoutSocket.cpp
  test/UnitTimeoutWSPing.cpp
  wsd/COOLWSD.cpp
Labels: 24.04

#10222 add option to the helm chart to configure wopi proof keys
  kubernetes/helm/collabora-online/templates/deployment.yaml
  kubernetes/helm/collabora-online/values.yaml
Labels: Hacktoberfest

#10254 Shows calc comment indicator as a triangle.
  browser/src/canvas/sections/CommentSection.ts
Labels: CODE "red"
