Repository CollaboraOnline/online, pull requests merged in 2024-07, with the labels that each got.

#9505 calc: fix edit and remove hypelink outside of edit mode
  browser/src/layer/tile/CanvasTileLayer.js
Labels: CODE "green"

#9506 CellCursorSection: Fix RTL case.
  browser/src/canvas/sections/CellCursorSection.ts
  browser/src/docstatefunctions.js
Labels: CODE "green"

#9493 default make run to use mount namespaces
  Makefile.am
  configure.ac
  cypress_test/Makefile.am
  test/run_unit.sh.in
  wsd/README.md
Labels: CODE "red"

#9450 broswer: sanitize productFAQ url
  browser/src/control/Control.UIManager.js
Labels: 23.05
