Repository CollaboraOnline/online, pull requests merged in 2024-08, with the labels that each got.

#9666 ci: github action for nightly docker
  .github/workflows/docker.yml
  docker/from-source-gh-action/Dockerfile
  docker/from-source-gh-action/README.md
  docker/from-source-gh-action/build.sh
  docker/from-source-gh-action/start-collabora-online.sh
Labels: enhancement, docker

#9796 draw/impress: Added Distribute commands
  browser/src/control/Control.ContextMenu.js
  browser/src/unocommands.js
Labels: 24.04

#9546 chore(android): Update Android Gradle Plugin
  android/app/build.gradle.in
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/res/layout/activity_document_browser.xml
  android/app/src/main/res/layout/file_list_item.xml
  android/app/src/main/res/values-b+ca+VALENCIA/strings.xml
  android/build.gradle.in
  android/gradle.properties
  android/gradle/wrapper/gradle-wrapper.properties
  android/lib/build.gradle.in
  android/lib/src/main/AndroidManifest.xml
  android/lib/src/main/res/values-b+ca+VALENCIA/strings.xml
  browser/Makefile.am
Labels: CODE "red"

#9794 Keyboard: Add Ctrl + Insert as Copy Shortcut
  browser/html/cool-help.html
  browser/src/map/handler/Map.Keyboard.js
Labels: 24.04

#9811 Meven/button notebookbar pointer
  browser/css/notebookbar.css
Labels: UX, design, CSS, 24.04

#9827 unobuttons: have cursor pointer also on buttons
  browser/css/notebookbar.css
Labels: bug, 24.04

#9722 duplicate _update() calls
  browser/src/layer/tile/CalcTileLayer.js
  browser/src/layer/tile/ImpressTileLayer.js
  browser/src/layer/tile/WriterTileLayer.js
Labels: CODE "red"

#9854 Prepare Online side for readonly comment editing.
  browser/src/control/Control.Menubar.js
  wsd/DocumentBroker.cpp
Labels: CODE "red"

#9896 Related: cool#9735 kit: use the new registerAnyInputCallback() LOK API
  kit/Kit.cpp
  kit/Kit.hpp
Labels: CODE "red"
