Repository CollaboraOnline/online, pull requests merged in 2025-07, with the labels that each got.

#12388 coolwsd.in: correct Action_InsertGraphic mention
  .gitpod-files/coolwsd-gitpod.xml
  coolwsd.xml.in
Labels: ready to merge

#12372 fix(android): allow opening documents after close
  wsd/COOLWSD.cpp
Labels: ready to merge, CODE "red"

#12362 ui: Clicking on the sheet status show the goto sheet dialog
  browser/src/control/jsdialog/Widget.HTMLContent.ts
Labels: CODE "red"

#12364 ui: Added menu entries for GotoPage/Slide/Sheet
  browser/src/control/Control.Menubar.ts
  browser/src/unocommands.js
Labels: CODE "red"

#12427 add a big plus cursor for spreadsheet and arrows when hovering over r…
  browser/css/spreadsheet.css
  browser/src/canvas/sections/AutoFillMarkerSection.ts
Labels: draft
