Repository CollaboraOnline/online, pull requests merged in 2025-08, with the labels that each got.

#12338 accessibility: adjusted width for jsdialog in format area ensuring labels are near to their input field
  browser/css/jsdialogs.css
Labels: draft, CODE "red"

#12524 Context toolbar: Fix button sizes
  browser/css/notebookbar.css
Labels: ready to merge

#12450 slide preview: keep focus on preview after deleting slide
  browser/src/control/Control.PartsPreview.js
Labels: ready to merge

#12643 add german function translations for the formula tab function dropdowns.
  browser/src/control/jsdialog/Definitions.Menu.ts
  browser/src/control/jsdialog/Definitions.Types.ts
Labels: draft

#12638 Feat: Add more button in notebookbar groups
  browser/css/btns.css
  browser/css/jssidebar.css
  browser/src/control/Control.NotebookbarCalc.js
  browser/src/control/Control.NotebookbarDraw.js
  browser/src/control/Control.NotebookbarImpress.js
  browser/src/control/Control.NotebookbarWriter.js
  browser/src/control/jsdialog/Definitions.Types.ts
  browser/src/control/jsdialog/Widget.OverflowGroup.ts
Labels: draft
